image: node:18

cache:
  key: ${CI_COMMIT_REF_SLUG}-node_modules
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  artifacts:
    paths:
      - public
  script:
    - npm install
    - npm test
