name: Decodr

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependendices
        run: npm install

      - name: Unit Test
        run: npm run test

      - name: Documentation Generation
        run: npm run docs

      - name: Documentationn Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    needs: build
    steps:
      - name: Deploy to GitHub page
        uses: actions/deploy-pages@v2

